### PR TITLE
Fix AvatarContract saving

### LINKED ISSUE #213: GraphQL error: Null value resolved for non-null field `address`
running the following query:
 ```
{
            avatarContracts {
              address
            }
          }
```

### PR DESCRIPTION
**Pull request by ben-kaufman**
Fix #213

### CODE REVIEW

**Comment by orenyodfat** [comment]
please add test to verify that

**Comment by ben-kaufman** [comment]
I'm not sure it's possible to test this scenario, this happens only for a moment and we already have a test for `avatarContracts`.

**Comment by orenyodfat** [comment]
What happend in this moment ?

**Comment by ben-kaufman** [comment]
I'm pretty sure it's before the first scheme is registered but the Avatar ownership was already transferred. I think I can add this check to the start of the domain test but this would be pretty strange for the test as this belongs to the Avatar and not domain testing.

**Comment by orenyodfat** [comment]
the avatar ownership will be transferred before the first scheme is registered most of the times.

**Comment by ben-kaufman** [comment]
Ok, but how would you suggest to write a good test for that?

**Comment by orenyodfat** [comment]
how this issue happened?

**Comment by ben-kaufman** [comment]
It happened because the code to save the Avatar was present twice, but was saving the full data needed only once. I just changed it to do save it a single time.

**Pull request merged**
